services:
  - type: web
    name: spotter-hos-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.3"
